defaults:

    # The default datamodel for sources if not specified below
    src_datamodel: cf
    # The datamodel convention (axes names, directions) for output coordinates
    dst_datamodel: cds

    units:
        # these are units to be used in fixes to simplify fixes
        shortname:
            mass_flux:  kg m-2 s-1
            radiation_flux: W m-2
            temperature: K
        # in the case you have strange units not recognized by the metpy
        # you can add them here
        fix:
            '1': 'dimensionless'
            'deg C': 'degC'
            'mm 3h-1': 'mm/(3h)'
            'm of water equivalent': 'm'
            'm of water s**-1': 'm s**-1'
            'm of water': 'm'
            'C': 'degC'
            '(0 - 1)': 'frac'
            'Celsius': 'degC'
            '0.001': 'g kg**-1'
            '1e-3': 'g kg**-1'
