# The first model in this block can be overridden
# in the command line by using:
# --model, --exp, --source, --outputdir, --catalog
# as an example two Zonal mean
models:
  - model: 'IFS-NEMO'
    exp: 'historical-1990'
    source: 'aqua-zonalmean'
  - model: 'IFS-NEMO'
    exp: 'historical-1990'
    source: 'aqua-zonalmean'

outputdir: "./"

# This is the variable that will be plotted from aqua-analysis output

region: 'arctic'
variable: 'so'

zonalmean_plot_params:
  figure_size: [15,15]
  plot_label: True
  plot_std: True
  unit:
  pdf_save: True
  mean_plot_title: 'Mean of Ensemble of Zonal average' 
  std_plot_title:  'Standard deviation of Ensemble of Zonal average' 
  cbar_label: 'temperature in K'
  


