# The first model in this block can be overridden
# in the command line by using:
# --model, --exp, --source, --outputdir, --catalog

# This yaml file will only have either annual or monthly
datasets:
  - catalog: null
    model: 'IFS-NEMO'
    exp: 'historical-1990'
    source: 'aqua-timeseries-monthly'
  - catalog: null  
    model: 'IFS-FESOM'
    exp: 'historical-1990'
    source: 'aqua-timeseries-monthly' 
  - catalog: null
    model: 'IFS-NEMO'
    exp: 'historical-1990'
    source: 'aqua-timeseries-annual'
  - catalog: null
    model: 'IFS-FESOM'
    exp: 'historical-1990'
    source: 'aqua-timeseries-annual'

# Reference
references:
  - catalog: null  
    model: 'ERA5'
    exp: 'era5'
    source: 'aqua-timeseries-monthly'
  - catalog: null  
    model: 'ERA5'
    exp: 'era5'
    source: 'aqua-timeseries-annual'

setup:
  loglevel: 'WARNING'

output:
  outputdir: "./"
  #rebuild: true
  save_netcdf: true
  save_pdf: true
  save_png: true
  #dpi: 300

diagnostics:
  ensemble:
    run: true
    diagnostic_name: 'EnsembleTimeseries'
    variable: '2t'
    params:
      default:
        startdate_data: "1990-01-01"
        enddate_data: "2005-01-01"
        startdate_ref: "1990-01-01"
        enddate_ref: "2005-01-01"
    plot_params:
      default:
        title: "Multi-Model Ensemble Statistics"
        plot_ensemble_members: False
