# The first model in this block can be overridden
# in the command line by using:
# --model, --exp, --source, --outputdir, --catalog
datasets:
  - catalog: 'climatedt-phase1' # null
    model: 'IFS-NEMO'
    exp: 'historical-1990'
    source: 'aqua-atmglobalmean'
  - catalog: 'nextgems4' # null
    model: 'IFS-FESOM'
    exp: 'historical-1990'
    source: 'aqua-atmglobalmean'

setup:
  loglevel: 'WARNING'

output:
  outputdir: "./"
  #rebuild: true
  save_netcdf: true
  save_pdf: true
  save_png: true
  dpi: 300

diagnostics:
  ensemble:
    run: true
    diagnostic_name: 'EnsembleLatLon'
    variable: '2t'
    params:
      default:
    plot_params:
      default:
        mean_title: 'Map of 2t for Ensemble Multi-Model mean'
        std_title: 'Map of 2t for Ensemble Multi-Model standard deviation'
        cbar_label: '2 meter temperature in K'  

