# codecov.yml
coverage:
  status:
    project:
      default:
        target: 55%   
        threshold: 0.1%  # Allow a 0.1% drop without failing
    
fixes:
  - "/__w/AQUA/AQUA/AQUA/src/::src/"

ignore:
  - "tests/*"          # Ignore test files
  - "diagnostics/*"     # Ignore diagnostics
  - "cli/*"            # Ignore CLI scripts

comment:
  layout: "diff, flags"
  require_changes: true
