# Configuration file of the teleconnections diagnostic
# This is the setup used to run the CI/CD tests
#
# Parameters in common to the teleconnections are:
#
# telec_type: 'station' or 'region' choose the 
#             function to use to compute the teleconnection
# field: field used to compute the teleconnection

# NAO coordinates
NAO:
  telec_type: 'station'
  field: msl
  lat1: 37.7
  lon1: -25.7
  lat2: 64.1
  lon2: -22

# Fake teleconnection for CI/CD tests
ENSO:
  telec_type: 'region'
  field: skt
  latN:  5
  lonW: -170
  latS: -5
  lonE: -120
