#!/bin/bash
#SBATCH --partition=shared
#SBATCH --job-name=weights_16
#SBATCH --output=weights_%j.out
#SBATCH --error=weights_%j.err
#SBATCH --account=bb1153
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --time=08:00:00
#SBATCH --mem=200G 
set -e

# find mamba/conda (to be refined)
whereconda=$(which mamba | rev | cut -f 3-10 -d"/" | rev)
source $whereconda/etc/profile.d/conda.sh

# activate conda environment
conda activate aqua

./generate_weights.py