datasets:
  - catalog: null
    model: FESOM
    exp: hpz3
    source: monthly-3d
    regrid: r100
    # reader_kwargs: {}

output:
  outputdir: "./"
  rebuild: true
  save_netcdf: true
  save_pdf: true
  save_png: true
  dpi: 300

diagnostics:
  ocean_drift:
    hovmoller:
      diagnostic_name: 'ocean3d'
      run: true
      var: ['thetao', 'so']
      regions: ['io', 'sss']
      dim_mean: ['lat', 'lon']
