# Create the environment:
# mamba env create -f environment.yml 
# or if you really want to use conda
# conda env create -f environment.yml

name: aqua
channels:
  - conda-forge
  - nodefaults
# please note that some of these dependencies are made explicit on purpose, but are not directly required by conda/mamba
dependencies:
  - python>=3.10,<3.13
  - cdo>=2.5.0
  - eccodes==2.41.0
  - pandas
  - pip
  - hdf5 #explicit to avoid issues with pypi
  - tempest-extremes # for TCs
  - xesmf # for ECmean
  - intake-esm
  - imagemagick
