# Create the environment:
# mamba env create -f environment.yml 
# or if you really want to use conda
# conda env create -f environment.yml

name: aqua
channels:
  - conda-forge
# please note that some of these dependencies are made explicit on purpose, but are not directly required by conda/mamba
dependencies:
  - python>=3.9,<3.13
  - cdo>=2.2.0
  - eccodes==2.39.0
  - pandas      
  - pandoc
  - pip
  - hdf5 #explicit to avoid issues with pypi
  - python-cdo # for teleconnections
  - tempest-extremes # for TCs
  - xesmf # for ECmean
  - intake-esm
  - imagemagick
