datasets:
  - catalog: null
    model: null
    exp: null
    source: null
    regrid: null
    freq: null # if the diagnostic supports it
  # Possible second/third/fourth datasets here, no present by default
  # - catalog: 'obs'
  #   model: 'ERA5'
  #   exp: 'era5'
  #   source: 'monthly'
  #   regrid: r100

references:
  - catalog: 'obs'
    model: 'ERA5'
    exp: 'era5'
    source: 'monthly'
    regrid: null

output:
  outputdir: "./"
  rebuild: true
  save_netcdf: true
  save_pdf: true
  save_png: true
  dpi: 300

diagnostics:
  teleconnections:
    NAO:
      run: false
      diagnostic_name: 'nao'
      months_window: 3
      seasons: ['DJF']
      cbar_range: [-5, 5]
    ENSO:
      run: true
      diagnostic_name: 'enso'
      months_window: 3
      seasons: ['annual']
      cbar_range: [-2, 2]