#!/usr/bin/env python3
"""Simple command line tool to execute a md5 checksum on grid files"""

import os
import hashlib
import argparse
import sys
from datetime import datetime
from aqua.util import ConfigPath, load_yaml

# default grids to be scanned by the grids-checker tool
GRIDS_FOLDERS = ['EN4', 'ERA5', 'FESOM', 'HealPix', 'ICON', 'IFS', 'lonlat',
                 'NEMO', 'OSI-SAF', 'PSC', 'WOA18']

def compute_md5(file_path):
    """Compute the MD5 checksum of a file."""
    hash_md5 = hashlib.md5()
    try:
        with open(file_path, "rb") as f:
            for chunk in iter(lambda: f.read(4096), b""):
                hash_md5.update(chunk)
        return hash_md5.hexdigest()
    except FileNotFoundError:
        return None

def generate_checksums(folder, grids, output_file):
    """Generate MD5 checksums for all files in a folder."""

    print(f"Generating datachecker to {output_file}...")
    current_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(output_file, "w", encoding='utf8') as f:
        f.write("# MD5 checksum file for AQUA-grids\n")
        f.write(f"# Folder: {folder}\n")
        f.write(f"# Generated by grid-checker.py on {current_date} \n\n")

        for grid_path in sorted(grids):
            subdir_path = os.path.join(folder, grid_path)
            if os.path.isdir(subdir_path):
                for root, _, files in os.walk(subdir_path):
                    for file in sorted(files):
                        file_path = os.path.join(root, file)
                        print(f"Computing checksum for {file_path}" )
                        md5_checksum = compute_md5(file_path)
                        if md5_checksum:
                            relative_path = os.path.relpath(file_path, folder)
                            f.write(f"{md5_checksum} {relative_path}\n")
    print(f"Checksum file created at {output_file}")

def verify_checksums(folder, checksum_file):
    """Verify files against MD5 checksums in the checksum file."""
    try:
        with open(checksum_file, "r", encoding='utf8') as f:
            print(f"Stating verification against {checksum_file}. It will take a while...")
            all_good = True
            for line in f:
                if line.startswith("#") or not line.strip():
                    continue
                md5_checksum, relative_path = line.strip().split(" ", 1)
                file_path = os.path.join(folder, relative_path)
                if not os.path.exists(file_path):
                    print(f"Missing file: {relative_path}!!")
                    all_good = False
                else:
                    computed_md5 = compute_md5(file_path)
                    if computed_md5 != md5_checksum:
                        print(f"Checksum mismatch for {relative_path}")
                        all_good = False
            if all_good:
                print("All files are verified successfully.")
            else:
                sys.exit("Verification failed.")
    except FileNotFoundError:
        sys.exit(f"Checksum file {checksum_file} not found.")

def main():
    parser = argparse.ArgumentParser(description="MD5 checksum utility for folders.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    config = ConfigPath()
    grids_path = load_yaml(config.machine_file)[config.machine]['paths']['grids']
    output_path = os.path.join(config.configdir, "datachecker", "grids-datacheck.md5")

    # Subcommand for generating checksums
    parser_generate = subparsers.add_parser("generate", help="Generate a checksum file.")
    parser_generate.add_argument("-o", "--output", default=output_path, help="Output checksum file.")

    # Subcommand for verifying checksums
    parser_verify = subparsers.add_parser("verify", help="Verify files using a checksum file.")
    parser_verify.add_argument("-c", "--checksum", default=output_path, help="Checksum file to verify against.")

    args = parser.parse_args()


    if args.command == "generate":
        generate_checksums(folder=grids_path, grids=GRIDS_FOLDERS, output_file=args.output)
    elif args.command == "verify":
        verify_checksums(folder=grids_path, checksum_file=args.checksum)

if __name__ == "__main__":
    main()
