grids:
  # FESOM oceanic healpix before 2023 update in land-sea-mask.
  # used in initial runs for ClimateDT phase1 
  fesom-NG5-hpz5-nested-v1:
    cdo_options: "--force"
    space_coord: ["ncells"]
    path: '{{ grids }}/HealPix/fesom-NG5_hpz5_nested_oce_v1.nc'
  fesom-NG5-hpz5-nested-3d-v1:
    cdo_options: "--force"
    path: 
      level: '{{ grids }}/HealPix/fesom-NG5_hpz5_nested_oce_level_v1.nc'
    space_coord: ["ncells"]
    vert_coord: ["level"]
  # for hpz7, 53512 missing values
  fesom-NG5-hpz7-nested-v1:
    cdo_options: "--force"
    space_coord: ["ncells"]
    path: '{{ grids }}/HealPix/fesom-NG5_hpz7_nested_oce_v1.nc'
  fesom-NG5-hpz7-nested-3d-v1:
    cdo_options: "--force"
    path:
      level: '{{ grids }}/HealPix/fesom-NG5_hpz7_nested_oce_level_v1.nc'
    space_coord: ["ncells"]
    vert_coord: ["level"]
  # for hpz9, 923769 missing values
  fesom-NG5-hpz9-nested-v1:
    cdo_options: "--force"
    space_coord: ["ncells"]
    path: '{{ grids }}/HealPix/fesom-NG5_hpz9_nested_oce_v1.nc'
  fesom-NG5-hpz9-nested-3d-v1:
    cdo_options: "--force"
    path:
      level: '{{ grids }}/HealPix/fesom-NG5_hpz9_nested_oce_level_v1.nc'
    space_coord: ["ncells"]
    vert_coord: ["level"]
  fesom-D3-hpz7-nested:
    cdo_options: "--force"
    space_coord: ["ncells"]
    path: '{{ grids }}/HealPix/fesom-D3_hpz7_nested_oce.nc'
  fesom-D3-hpz7-nested-3d:
    cdo_options: "--force"
    path:
      level: '{{ grids }}/HealPix/fesom-D3_hpz7_nested_oce_level.nc'
    space_coord: ["ncells"]
    vert_coord: ["level"]

  # FESOM oceanic healpix after 2023 update in land-sea-mask.
  # Notice that these are different from those above due to different land-sea mask
  # Used in NextGEMS cycle4 and ClimateDT phase2
  # for hpz7, 57831 missing values
  fesom-NG5-hpz7-nested-v2:
    cdo_options: "--force"
    space_coord: ["ncells"]
    path: '{{ grids }}/HealPix/fesom-NG5_hpz7_nested_oce_v2.nc'
  fesom-NG5-hpz7-nested-3d-v2:
    cdo_options: "--force"
    path:
      level: '{{ grids }}/HealPix/fesom-NG5_hpz7_nested_oce_level_v2.nc'
    space_coord: ["ncells"]
    vert_coord: ["level"]
  # for hpz9, 984749 missing values
  fesom-NG5-hpz9-nested-v2:
    cdo_options: "--force"
    space_coord: ["ncells"]
    path: '{{ grids }}/HealPix/fesom-NG5_hpz9_nested_oce_v2.nc'
  fesom-NG5-hpz9-nested-3d-v2:
    cdo_options: "--force"
    path:
      level: '{{ grids }}/HealPix/fesom-NG5_hpz9_nested_oce_level_v2.nc'
    space_coord: ["ncells"]
    vert_coord: ["level"]
  fesom-NG5-hpz10-nested-v2:
    cdo_options: "--force"
    space_coord: ["ncells"]
    path: '{{ grids }}/HealPix/fesom-NG5_hpz10_nested_oce_v2.nc'
  fesom-NG5-hpz10-nested-3d-v2:
    cdo_options: "--force"
    path:
      level: '{{ grids }}/HealPix/fesom-NG5_hpz10_nested_oce_level_v2.nc'
    space_coord: ["ncells"]
    vert_coord: ["level"]
  
  # FESOM v3: These are grids for DestinE O-25.1 cycle.
  # Interpolation to HealPix is now conservative and this
  # produced a change in the land sea mask, so all the grids
  # are different from the previous ones
  fesom-NG5-hpz10-nested-v3:
    cdo_options: "--force"
    space_coord: ["ncells"]
    path: '{{ grids }}/FESOM/fesom-NG5_hpz10_nested_oce_v3.nc'
  fesom-NG5-hpz10-nested-3d-v3:
    cdo_options: "--force"
    path:
      level: '{{ grids }}/FESOM/fesom-NG5_hpz10_nested_oce_level_v3.nc'
    space_coord: ["ncells"]
    vert_coord: ["level"]
  fesom-NG5-hpz9-nested-v3:
    cdo_options: "--force"
    space_coord: ["ncells"]
    path: '{{ grids }}/FESOM/fesom-NG5_hpz9_nested_oce_v3.nc'
  fesom-NG5-hpz9-nested-3d-v3:
    cdo_options: "--force"
    path:
      level: '{{ grids }}/FESOM/fesom-NG5_hpz9_nested_oce_level_v3.nc'
    space_coord: ["ncells"]
    vert_coord: ["level"]
  fesom-NG5-hpz7-nested-v3:
    cdo_options: "--force"
    space_coord: ["ncells"]
    path: '{{ grids }}/FESOM/fesom-NG5_hpz7_nested_oce_v3.nc'
  fesom-NG5-hpz7-nested-3d-v3:
    cdo_options: "--force"
    path:
      level: '{{ grids }}/FESOM/fesom-NG5_hpz7_nested_oce_level_v3.nc'
    space_coord: ["ncells"]
    vert_coord: ["level"]
  fesom-CORE2-hpz5-nested-v3:
    cdo_options: "--force"
    space_coord: ["ncells"]
    path: '{{ grids }}/FESOM/fesom-CORE2_hpz5_nested_oce_v3.nc'
  fesom-CORE2-hpz5-nested-3d-v3:
    cdo_options: "--force"
    path:
      level: '{{ grids }}/FESOM/fesom-CORE2_hpz5_nested_oce_level_v3.nc'
    space_coord: ["ncells"]
    vert_coord: ["level"]
  fesom-D3-hpz7-nested-v3:
    cdo_options: "--force"
    space_coord: ["ncells"]
    path: '{{ grids }}/FESOM/fesom-D3_hpz7_nested_oce_v3.nc'
  fesom-D3-hpz7-nested-3d-v3:
    cdo_options: "--force"
    path:
      level: '{{ grids }}/FESOM/fesom-D3_hpz7_nested_oce_level_v3.nc'
    space_coord: ["ncells"]
    vert_coord: ["level"]
  
  #FESOM
  ng5-nodes-2d:
    path: '{{ grids }}/FESOM/AQUA_NG5_griddes_nodes_IFS.nc'
    space_coord: ["nod2"]
  ng5-nodes-3d:
    path:
      nz: '{{ grids }}/FESOM/NG5_nodes_fesom_mask_nz.nc'
      nz1: '{{ grids }}/FESOM/NG5_nodes_fesom_mask_nz1.nc'
    space_coord: ["nod2"]
    vert_coord: ["nz", "nz1"]
    cdo_extra: 
    - -setgrid,'{{ grids }}/FESOM/NG5_griddes_nodes_IFS.nc' 
  ng5-elems-2d:
    space_coord: ['elem']
    cdo_extra: 
    - -setgrid,'{{ grids }}/FESOM/NG5_griddes_elems_IFS.nc' 
  ng5-elems-3d:
    path:
      nz1: '{{ grids }}/FESOM/NG5_elem_fesom_mask_nz1.nc'
    space_coord: ["elem"]
    vert_coord: ["nz1"]
    cdo_extra: 
    - -setgrid,'{{ grids }}/FESOM/NG5_griddes_elems_IFS.nc'

  # FESOM interpolated
  fesom-interpolated-2d:
    path: '{{ grids }}/FESOM/fesom_tco2559_interpolated_2d.nc'
    space_coord: ["lon", "lat"]
  fesom-interpolated-3d:
    path: '{{ grids }}/FESOM/fesom_tco2559_interpolated_3d.nc'
    space_coord: ["lon", "lat"]
    vert_coord: depth