grids:
  # NEMO oceanic Healpix: each ORCA grid needs its definition due to changing LSM
  # Used in ClimateDT phase1
  nemo-eORCA1-hpz5-nested:
    cdo_options: --force
    space_coord: [ncells]
    path: '{{ grids }}/HealPix/nemo-eORCA1_hpz5_nested_oce.nc'
  nemo-eORCA1-hpz5-nested-3d:
    cdo_options: --force
    path:
      level: '{{ grids }}/HealPix/nemo-eORCA1_hpz5_nested_oce_level.nc'
    space_coord: [ncells]
    vert_coord: [level]
  nemo-eORCA025-hpz7-nested:
    cdo_options: --force
    space_coord: [ncells]
    path: '{{ grids }}/HealPix/nemo-eORCA025_hpz7_nested_oce.nc'
  nemo-eORCA025-hpz7-nested-3d:
    cdo_options: --force
    path:
      level: '{{ grids }}/HealPix/nemo-eORCA025_hpz7_nested_oce_level.nc'
    space_coord: [ncells]
    vert_coord: [level]
  nemo-eORCA12-hpz7-nested:
    cdo_options: --force
    space_coord: [ncells]
    path: '{{ grids }}/HealPix/nemo-eORCA12_hpz7_nested_oce.nc'
  nemo-eORCA12-hpz7-nested-3d:
    cdo_options: --force
    path:
      level: '{{ grids }}/HealPix/nemo-eORCA12_hpz7_nested_oce_level.nc'
    space_coord: [ncells]
    vert_coord: [level]
  nemo-eORCA12-hpz10-nested:
    cdo_options: --force
    space_coord: [ncells]
    path: '{{ grids }}/HealPix/nemo-eORCA12_hpz10_nested_oce.nc'
  nemo-eORCA12-hpz10-nested-3d:
    cdo_options: --force
    path:
      level: '{{ grids }}/HealPix/nemo-eORCA12_hpz10_nested_oce_level.nc'
    space_coord: [ncells]
    vert_coord: [level]
  # NEMO v3: These are grids for DestinE O-25.1 cycle.
  # Interpolation to HealPix is now conservative and this
  # produced a change in the land sea mask, so all the grids
  # are different from the previous ones
  nemo-eORCA12-hpz10-nested-v3:
    cdo_options: --force
    space_coord: [ncells]
    path: '{{ grids }}/NEMO/nemo-eORCA12_hpz10_nested_oce_v3.nc'
  nemo-eORCA12-hpz10-nested-3d-v3:
    cdo_options: --force
    path:
      level: '{{ grids }}/NEMO/nemo-eORCA12_hpz10_nested_oce_level_v3.nc'
    space_coord: [ncells]
    vert_coord: [level]
  nemo-eORCA12-hpz9-nested-v3:
    cdo_options: --force
    space_coord: [ncells]
    path: '{{ grids }}/NEMO/nemo-eORCA12_hpz9_nested_oce_v3.nc'
  nemo-eORCA12-hpz9-nested-3d-v3:
    cdo_options: --force
    path:
      level: '{{ grids }}/NEMO/nemo-eORCA12_hpz9_nested_oce_level_v3.nc'
    space_coord: [ncells]
    vert_coord: [level]
  nemo-eORCA12-hpz7-nested-v3:
    cdo_options: --force
    space_coord: [ncells]
    path: '{{ grids }}/NEMO/nemo-eORCA12_hpz7_nested_oce_v3.nc'
  nemo-eORCA12-hpz7-nested-3d-v3:
    cdo_options: --force
    path:
      level: '{{ grids }}/NEMO/nemo-eORCA12_hpz7_nested_oce_level_v3.nc'
    space_coord: [ncells]
    vert_coord: [level]
  nemo-eORCA1-hpz5-nested-v3:
    cdo_options: --force
    space_coord: [ncells]
    path: '{{ grids }}/NEMO/nemo-eORCA1_hpz5_nested_oce_v3.nc'
  nemo-eORCA1-hpz5-nested-3d-v3:
    cdo_options: --force
    path:
      level: '{{ grids }}/NEMO/nemo-eORCA1_hpz5_nested_oce_level_v3.nc'
    space_coord: [ncells]
    vert_coord: [level]
  # Grids from the multiIO r360x181 conservative interpolation from eORCA025
  nemo-eORCA025-r100s-v3:
    path: '{{ grids }}/NEMO/nemo-eORCA025-r100s_v3.nc'
  nemo-eORCA025-r100s-3d-v3:
    path:
      level: '{{ grids }}/NEMO/nemo-eORCA025-r100s-3d_v3.nc'


  # NEMO
  eORCA1-2d:
    path: '{{ grids }}/NEMO/eORCA1_mesh_sfc_grid_T.nc'
  eORCA1-3d-level:
    path:
      level: '{{ grids }}/NEMO/eORCA1_mesh_3d_grid_T_level.nc'
    space_coord: [ncells]
    vert_coord: [level]
  eORCA1-3d-height:
    path:
      height: '{{ grids }}/NEMO/eORCA1_mesh_3d_grid_T_level.nc'
    space_coord: [ncells]
    vert_coord: [height]
  eORCA025-2d:
    path: '{{ grids }}/NEMO/eORCA025_mesh_sfc_grid_T.nc'
  eORCA025-3d-level:
    path:
      level: '{{ grids }}/NEMO/eORCA025_mesh_3d_grid_T_level.nc'
    space_coord: [ncells]
    vert_coord: [level]
  eORCA025-3d-height:
    path:
      height: '{{ grids }}/NEMO/eORCA025_mesh_3d_grid_T_level.nc'
    space_coord: [ncells]
    vert_coord: [height]
  eORCA12-2d:
    path: '{{ grids }}/NEMO/eORCA12_mesh_sfc_grid_T.nc'
  eORCA12-3d-level:
    path:
      level: '{{ grids }}/NEMO/eORCA12_mesh_3d_grid_T_level.nc'
    space_coord: [ncells]
    vert_coord: [level]
  eORCA12-3d-height:
    path:
      height: '{{ grids }}/NEMO/eORCA12_mesh_3d_grid_T_level.nc'
    space_coord: [ncells]
    vert_coord: [height]
  nemo-healpix:
    path:
      2d: '{{ grids }}/HealPix_old/nemo_hpx10_oce_2d.nc'
      level: '{{ grids }}/HealPix_old/nemo_hpx10_oce_level.nc'
    space_coord: [ncells]
    vert_coord: [level]
  nemo-multiIO-r025:
    path: '{{ grids }}/lonlat/nemo-multiIO-r025.nc'
  nemo-multiIO-r025-3d:
    path:
      level: '{{ grids }}/lonlat/nemo-multiIO-r025-3d.nc'
  nemo-multiIO-r100:
    path: '{{ grids }}/lonlat/nemo-multiIO-r100.nc'
  nemo-multiIO-r100-3d:
    path:
      level: '{{ grids }}/lonlat/nemo-multiIO-r100-3d.nc'
