# Template according to #1613
# The first model in this block can be overridden
# in the command line by using:
# --model, --exp, --source, --outputdir, --catalog
datasets:
  - catalog: null
    model: null
    exp: null
    source: 'lra-r100-monthly'
    regrid: null
  # Possible second/third/fourth datasets here, no present by default
  # - catalog: 'obs'
  #   model: 'ERA5'
  #   exp: 'era5'
  #   source: 'monthly'
  #   regrid: r100

references:
  - catalog: 'obs'
    model: 'ERA5'
    exp: 'era5'
    source: 'monthly'
    regrid: null

output:
  outputdir: "./"
  rebuild: true
  save_pdf: true
  save_png: true
  dpi: 300

diagnostics:
  seasonalcycles:
    run: true
    diagnostic_name: 'atmosphere'
    variables: ['2t', 'tprate', 'ie', 'msl',
                 'tcc', 'lcc', 'mcc', 'hcc',
                 'slhtf', #Mean surface latent heat flux
                 'ishf', #Mean surface sensible heat flux
                 'sdswrf', #Mean surface downward short-wave radiation flux
                 'sdlwrf', #Mean surface downward long-wave radiation flux
                 'snswrf', #Mean surface net short-wave radiation flux
                 'snlwrf', #Mean surface net long-wave radiation flux
                 'tnlwrf', #Mean top net long-wave radiation flux
                 'tnswrf' #Mean top net short-wave radiation flux
                 ]
    params:
      default:
        std_startdate: '19900101'
        std_enddate: '20201231'
      tprate:
        units: "mm/day"
