#!/bin/bash

#SBATCH -A project_465000454
#SBATCH --cpus-per-task=1
#SBATCH -n 32
#SBATCH -t 0-00:30:00 #change the wallclock
#SBATCH -J aqua_jupyter
#SBATCH --output=/users/pghinass/AQUA/diagnostics/tropical_cyclones/slurm_jobs/TC_slurm_%j.out
#SBATCH --error=/users/pghinass/AQUA/diagnostics/tropical_cyclones/slurm_jobs/TC_slurm_%j.err
#SBATCH -p dev-g    #change the partition

set -e
# directory of python script to execute
DIR=/users/pghinass/AQUA/diagnostics/tropical_cyclones/cli
python $DIR/tropical_cyclones_cli.py
