# Template according to #1613
# The first model in this block can be overridden
# in the command line by using:
# --model, --exp, --source, --outputdir, --catalog
datasets:
  - catalog: null
    model: null
    exp: null
    source: 'lra-r100-monthly'
    regrid: null
  # Possible second/third/fourth datasets here, no present by default
  # - catalog: 'obs'
  #   model: 'ERA5'
  #   exp: 'era5'
  #   source: 'monthly'
  #   regrid: r100

references:
  - catalog: 'obs'
    model: 'CERES'
    exp: 'ebaf-toa41'
    source: 'monthly'
    regrid: null

output:
  outputdir: "./"
  rebuild: true
  save_pdf: true
  save_png: true
  dpi: 300

diagnostics:
  timeseries:
    run: true
    variables: ['tnlwrf', 'tnswrf']
    formulae: ['tnlwrf+tnswrf']
    params:
      default:
        hourly: False
        daily: False
        monthly: True
        annual: True
        std_startdate: '20000101'
        std_enddate: '20201231'
      tnlwrf+tnswrf:
        standard_name: "net_top_radiation"
        long_name: "Net top radiation"
      

# This is the list of variables that will be plotted as timeseries
timeseries: ['tnlwrf', 'tnswrf']
timeseries_formulae: ['tnlwrf+tnswrf']
