# The first model in this block can be overridden
# in the command line by using:
# --model, --exp, --source, --outputdir, --catalog
models:
  - catalog: null
    model: 'IFS-NEMO'
    exp: 'historical-1990'
    source: 'lra-r100-monthly'

output:
  outputdir: "./"
  rebuild: true
  filename_keys: null # or, for example,  ['diagnostic', 'catalog', 'model', 'diagnostic_product', 'var']
  save_netcdf: true
  save_pdf: true
  save_png: true
  dpi: 300

# This is the list of variables that will be plotted as timeseries
timeseries: ['tnlwrf', 'tnswrf']
timeseries_formulae: ['tnlwrf+tnswrf']

gregory:
  ts: '2t'
  toa: ['tnlwrf', 'tnswrf']
  monthly: True
  annual: True

timeseries_plot_params:
# These are options that specify how the data is plotted
# Default values are used if the variable that is being
# plotted is not specified here.
# If you need specific options for a variable, you can
# add it here.
  default:
    plot_ref: True
    monthly: True
    annual: True
    std_startdate: '2000-01-01'
    std_enddate: '2020-12-31'
    regrid: null
    plot_ref_kw: { model: 'CERES', exp: 'ebaf-toa41', source: 'monthly'}

  tnlwrf+tnswrf:
    longname: "Net top radiation" # This is to override title and ylabel
    std_startdate: '2000-01-01'
    std_enddate: '2020-12-31'
    regrid: null
    plot_ref_kw: { model: 'CERES', exp: 'ebaf-toa41', source: 'monthly'}