# Choice of interface
interface: AQUA
# Choice of model name. It is printed in the output table
model:
  name: ClimateDT

# this block is not necessary within the AQUA integration
dirs:
  exp: null
  tab: null
  fig: null

global_mean:
  variables:
    atm: [tas, psl, pr, evspsbl, pme, clt, cll, clm, clh,
              pr_oce, pme_oce, pr_land, pme_land,
              rsnt, rlnt, net_toa, rsns, rlns, hfss, hfls]
    oce: [tos, sos]
    ice: [siconc]
    tab: []
  regions: ['Global', 'North Midlat', 'Tropical', 'South Midlat']
  seasons: ['ALL', 'DJF', 'JJA']
  reference: EC23

performance_indices:
  variables:
    atm2d: [net_sfc, tas, psl, pr, tauu, tauv]
    atm3d: [ta, ua, va, hus]
    oce: [tos, sos]
    ice: [siconc]
  regions: ['Global', 'North Midlat', 'Tropical', 'South Midlat']
  seasons: ['ALL', 'DJF', 'JJA']
  climatology: EC23
